### ISSUE TITLE
Talk about thread.h

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#39]
http://www.drdobbs.com/cpp/c-finally-gets-a-new-standard/232800444

New standard = new api for threads.

**Comment by angrave** [comment]
We should ask system faculty what they want from CS241. We shouldnt teach equivalent pthread AND C11 primitives.

For the short term let's continue to use pthreads since 99% of all C code today uses pthreads and its more portable (more platforms support it), and mention that the new C standard may be appropriate for new projects. See stackoverflow for reasons why people still prefer pthreads e.g. much more configurable (thread stack space, mutex types etc etc)

**Comment by bhuvy2** [comment]
Definitely, not saying that we switch the curriculum to `thread.h`. We mention openmp, so It would be good to mention other standards (could be cool to include the go model of concurrency as well).
