### ISSUE TITLE
Fork while keeping open `FILE*` handles

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/coursebook#40]
You shouldn't fork and then read. https://stackoverflow.com/questions/50110992/why-does-forking-my-process-cause-the-file-to-be-read-infinitely/50112169#50112169

Will close the issue, but we need to update the coursebook

**Comment by angrave** [comment]
I disagree with "You shouldn't fork and then read." as a general statement (all processes on a system are a result of fork/clone!). 
The problem is that recent versions of glibc call seek on input streams on exit even if you do explicitly nothing in a process. The fix (I argue HACK - yes Iknow the POSIX spec - I argue that calling seek on a the fd when the child does nothing is evil) is to call fflush(null) before fork

**Comment by angrave** [comment]
See
https://github-dev.cs.illinois.edu/angrave/cs241-lectures/blob/master/code/lec07/fork_exit_test.c
Which works (without any workarounds enabled) on early Linux glibv versions. e.g linux.ews.illinois.edu
- Do you want to file a regression bug with glibc

fflush(NULL) does not flush input files. You need to fflush all input streams.

**Comment by bhuvy2** [comment]
Hmm okay (this issue escaped my attention for a while).

So to backtrack on the issue, we should figure this out in a tiered way

The fork-filedescriptors-FILE requires a bunch of research trying the unify

* C Standard
* POSIX/Linux/Whatever Linus Torvalds was thinking
* Whatever Richard Stallman was thinking for glibc
* Whatever the Ubuntu Developers (this is so that students developing on VMs don't get confused).

The stack overflow answer is pretty detailed about POSIX, but we'll need a bit of research on the other few parts.
